id: uipath_signup
learningObjectives:
  - Create a UiPath account.
hints:
  - Visit [UiPath's sign-up page](https://www.uipath.com) to get started.
  - Make sure to verify your email address after signing up.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Hey there, it's Lucca! Ready for your automated debut?
          - text: First things first, we need to get you signed up and signed in at UiPath. UiPath Is like getting a library card—except this library helps us automate the world.
    - actionId: finish_step
trigger:
  type: user_ready_response