id: uipath_login
learningObjectives:
  - test
hints:
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Login to UIPath
          - components:
              - type: uipath_connect
trigger:
  type: user_event
  params:
    event: uipath_user_connected
  flowNode:
    do:
      - actionId: network_http_request
        name: get_user_org
        params:
          url: "https://cloud.uipath.com/identity_/api/UserOrgs/userOrgsLocalByAuth0Token"
          method: GET
          headers:
            Authorization: "Bearer ${user.integrations.uipath.accessToken}"
            "Content-Type": "application/json"
          params:
            includeNonAcceptedInvites: false

    if:
      conditions:
        - conditionId: is_truthy
          params:
            value: ${outputs.get_user_org?.data?.[0]?.name}
      then:
        do:
          - actionId: user_set_integration_property
            params:
              integration: uipath
              key: userOrg
              value: ${outputs.get_user_org.data[0].name}
          - actionId: network_http_request
            name: get_tenant
            params:
              url: "https://cloud.uipath.com/${outputs.get_user_org.data[0].name}/portal_/api/organization/tenant"
              method: GET
              headers:
                Authorization: "Bearer ${user.integrations.uipath.accessToken}"
                "Content-Type": "application/json"
              params:
                organizationGuid: ${outputs.get_user_org.data[0].globalId}
                accountName: ${outputs.get_user_org.data[0].name}
                includeTenantServices: true

        if:
          conditions:
            - conditionId: is_truthy
              params:
                value: ${outputs.get_tenant?.data?.[0]?.name}
          then:
            do:
              - actionId: user_set_integration_property
                params:
                  integration: uipath
                  key: tenantName
                  value: ${outputs.get_tenant.data[0].name}
              - actionId: user_set_integration_property
                params:
                  integration: uipath
                  key: userOrg
                  value: ${outputs.get_user_org.data[0].name}
              - actionId: network_http_request
                name: set_webhook
                params:
                  url: "https://cloud.uipath.com/${user.integrations.uipath.userOrg}/${user.integrations.uipath.tenantName}/orchestrator_/odata/Webhooks"
                  method: POST
                  headers:
                    Authorization: "Bearer ${user.integrations.uipath.accessToken}"
                    "Content-Type": "application/json"
                  data: 
                    Name: "WilcoUiPathEvent_${user.repoName}"
                    Url: "https://engine.wilco.gg/users/${user.id}/event?event=uipathevent"
                    Enabled: true
                    SubscribeToAllEvents: true
                    AllowInsecureSsl: true
                    Events: "[]"
            if:
              conditions:
                - conditionId: is_truthy
                  params:
                    value: ${outputs.set_webhook?.data?.name?}
              then:
                do:
                  - actionId: user_set_integration_property
                    params:
                      integration: uipath
                      key: webhook
                      value: ${outputs.set_webhook.data.Url}
                  - actionId: store_user_property
                    params:
                      name: uipathstudio
                      value: "https://cloud.uipath.com/${user.integrations.uipath.userOrg}/studio_"

                  - actionId: network_http_request
                    name: set_folders
                    params:
                      url: "https://cloud.uipath.com/${user.integrations.uipath.userOrg}/${user.integrations.uipath.tenantName}/orchestrator_/api/Folders/GetAllForCurrentUser"
                      method: GET
                      headers:
                        Authorization: "Bearer ${user.integrations.uipath.accessToken}"
                        "Content-Type": "application/json"
                if:
                  conditions:
                    - conditionId: is_truthy
                      params:
                        value: ${outputs.set_folders?.data?.PageItems[0].Id?}
                  then:
                    do:
                      - actionId: user_set_integration_property
                        params:
                          integration: uipath
                          key: OrganizationUnitId
                          value: ${outputs.set_folders.data.PageItems[0].Id}
                      - actionId: finish_step
                  
              else:
                do:
                  - actionId: bot_message
                    params:
                      person: lucca
                      messages:
                        - text: "Error while login to UIPath"



          else:
            do:
              - actionId: bot_message
                params:
                  person: lucca
                  messages:
                    - text: "Error while login to UIPath"
      else:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: "Error while login to UIPath"
