id: uipath_printvariabletoconsole
learningObjectives:
  - Create a flow to fill data into your variable
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Now that we've created our incredible variable, let's fill some data into it by creating a new step after our trigger
          - text: ":instruction[Click on the plus sign and search for `Set variable value` and click on it] and choose `theincrediblevariable`"
          - text: Now that you have an action in place, choose the variable that we've created from the dropdown.
          - text: We'll choose data from the manual trigger called `Job Data`, expand the object and choose `Robot name` as value
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Lets move on to see it in action.
      - actionId: finish_step
