id: uipath_log_data
learningObjectives:
  - Log data in test flow
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: We want to see some feedback from our flow, we'll use a new action called `Log Message`
          - text: We'll :instruction[Click on the [+] Plus sign] and search for `Log Message`
          - text: In the message input field choose your new variable `theincrediblevar` and log level as `Info`
    - actionId: bot_message
      params:
        person: lucca
        messages: 
          - text: Now its time to test your work :instruction[Click `Test on cloud` from top left corner] and see it in action.
          - text: I'm going to check how you did, once I validate it you'll be able to continue.
trigger:
  type: user_event
  params:
    event: uipathevent
  flowNode:
    do:
    - actionId: network_http_request
      name: robot_logs
      params:
        url: "https://cloud.uipath.com/${user.properties.uipath_orgName}/${user.properties.uipath_tenantName}/orchestrator_/odata/RobotLogs"
        method: GET
        data: 
          X-UIPATH-OrganizationUnitId: ${user.integrations.uipath.OrganizationUnitId}
          Authorization: "Bearer ${user.integrations.uipath.accessToken}"
    if:
      conditions:
        - conditionId: is_truthy
          params:
            value: "${outputs.robot_logs.data.value.find(item => item.Message === 'Mircea Eliade once said')}"
      then:
        do:
        - actionId: bot_message
          params:
            person: lucca
            messages:
            - text: "Lets do this! You managed to set everything up, print to console. Time to move to some advance things now."