id: uipath_variable_creation
learningObjectives:
  - Create and utilize a variable using Data Manager.
hints:
  - Check [Variable
    Creation](https://docs.uipath.com/studio/docs/managing-variables) in the
    UiPath docs for additional insights.
  - Always assign meaningful names to variables so Ness knows you’re organized!
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Now, let's take our creations further by setting up some variables.
          - text: If data cells were bees, variables would be the jars in which we store the
              honey.
          - text: "We'll create a new variable by :instruction[clicking the New+ button] and choosing variable and type text."
          - text: Name your new variable `theincrediblevariable`
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Now lets fill in some data and test it!
      - actionId: finish_step
